### ISSUE TITLE
Dummy broken?

### ISSUE THREAD

**Issue by tjikkun** [ngardiner/TWCManager#201]
I am correct that the Dummy interface doesn't work anymore? If so, is this something to add back?

**Comment by ngardiner** [comment]
It's a good question, the dummy interface was intended to give us testing capability and I don't recall the current state of it, but I'll take a look and get back to you.

**Comment by tjikkun** [comment]
I am working on this in https://github.com/tjikkun/TWCManager/tree/dummy

**Comment by awegmann** [comment]
Hi Nathan. I'm also interested in the dummy interface. I'm currently trying to implement a KNX command interface for TWCManager. And for testing my first intention was to disable the RS485 interface. But on startup I get immediately a failure because TWCManager tries to open the /dev/ttyUSB0 interface - even when this module is disabled. 
I can try to fix this, but I wonder if this should be the normal operation if I disable RS485 and enable dummy interface and if you just didn't use the dummy interface in the near past.

**Comment by awegmann** [comment]
@tjikkun What's the current state of your "dummy" branch? Can you provide a pull request and @ngardiner Nathan, can you accept the pull request? This is exactly what I was looking for to make the dummy interface usable.

**Comment by tjikkun** [comment]
Although I would like to do some more work to make dummy module more  useful, it can be merged as is, since it solves the immediate issue.
