### ISSUE TITLE
maxAmps always 32?

### ISSUE THREAD

**Issue by hopfi2k** [ngardiner/TWCManager#213]
I'm wondering why TWCManager shows 32 Amps always? Shouldn't this be overridden by `config.json`?

`16:58:20 TWCManager 1 32.00 amp slave TWC 6617 is ready to link.  Sign: 37`

In `config.json` I have:

`"wiringMaxAmpsAllTWCs": 24,` and `"wiringMaxAmpsPerTWC": 24,`

I'm trying to make use of `maxAmps` in the new UI. Should this be set to `wiringMaxAmpsPerTWC` as per config and not to 32A (which, I believe is the theoretical maximum the TWC can handle)?

**Comment by ngardiner** [comment]
```maxAmps``` is reported to us by the TWC, as different TWC hardware revisions/versions have different capabilities

```wiringMaxAmpsAllTWCs``` and ```wiringMaxAmpsPerTWC``` limit how much current we allocate for all TWCs or individual TWCs, so it represents the capability of the circuit (not the hardware)

It all depends on what you want to show. We show the max amperage of each TWC in the Web UI because that is a dynamic value and not something we can view/set in config (ie it is reported to us), just like the TWC ID, State, Version etc

I'm not sure that showing config variables is as important in the web UI, but maybe you can find a way to express it as ```maxAmps``` unless ```maxAmps``` is greater than ```wiringMaxAmpsPerTWC```? That would be **more** accurate but still not 100% accurate because it doesn't take into account ```wiringMaxAmpsAllTWCs``` which may limit current because there are other TWCs on the same circuit.
