### ISSUE TITLE
cancelChargeNow REST call doesn't stop charging

### ISSUE THREAD

**Issue by jherby2k** [ngardiner/TWCManager#254]
I'm just playing with the REST api for the first time. v1.2.1.

My car is not charging right now (tracking green energy, and its night time). If I issue a "chargeNow" call, it begins charging as expected. If I then issue a "cancelChargeNow" it seems to drop back down to 6 amps (my configured minimum) but doesn't stop charging.

cancelChargeNow should use the Tesla API to stop charging if charging was stopped initially. Right? bug?

Great work by the way! Just got this installed this afternoon without any hickups.

**Comment by ngardiner** [comment]
Hi @jherby2k!

What happens when you issue a chargeNow command is that the Charge Now policy takes precedence over whatever other policy would normally be running at that point in time, to charge at the specified rate for the specified time.

Once that time runs out or if you end it early with the cancelChargeNow call, it will fall back to whatever the policy would have been at that time. If it happens that the charge policy would charge at 6A (for example, if non-scheduled charging is set to 6A) then it would start charging at 6A afterwards, so it does depend on the policy active at the time.

What policy name does it show you after you execute the cancelChargeNow in the Web Interface or Console, is it Non-Scheduled Charging?

**Comment by jherby2k** [comment]
I may have just been impatient... will test again

**Comment by jherby2k** [comment]
Yeah you're right - sorry to waste your time. Just took 2 minutes or so to stop entirely.
