### ISSUE TITLE
[feature request] show offset separated from consumption

### ISSUE THREAD

**Issue by alexeiw123** [ngardiner/TWCManager#258]
I am using an offset of 720W (1A *3phase) with enphase API integration as it gives a bit of headroom for loads to not cause import from the grid. It would be great if the consumption readout was accurate from the EMS, with the offset called out separately in either the consumption or solar surplus area.

**Comment by ngardiner** [comment]
We do record it separately internally as "Manual" consumption vs consumption fetched from an EMS module, so that the values captured via the EMS and the value via the offset are kept separate but then represented as one value via all of the external interfaces.

The challenge is how exactly we'd show it - there's always a tradeoff between detail and usability and with the new web interface we have to some degree reduced the detail in order to simplify the interface. So knowing where to reflect this detail is the most important part - is it something that belongs in the Web UI, in the console output, or maybe as a dedicated view/API/MQTT topic/etc to see the generation or consumption details broken down further is probably the key for us to determine.
