### ISSUE TITLE
TWCID no longer converted to decimal

### ISSUE THREAD

**Issue by MikeBishop** [ngardiner/TWCManager#269]
Trying the `vin_mgmt` branch, as suggested on #263, but this might be present in other current branches as well.  (I've been sitting on `error_backoff` for a while.)  I'm seeing the following in the console output:
![image](https://user-images.githubusercontent.com/4273797/116139580-2aedb180-a6a4-11eb-8c9a-e43b203efb93.png)

Should this have shown as a number instead?

**Comment by ngardiner** [comment]
This would be a regression from the introduction of the Python logger module, which is representing the value as a bytearray now instead of hexadecimal. It would either be for 2 reasons - either we lost the explicit translation from bytes to hex during the migration over to the ```logging``` module, or we were relying on previous implicit translation that has now gone away. I'll investigate further.

**Comment by ngardiner** [comment]
Took me a while, but fixed this in 4e8b825
