### ISSUE TITLE
Documentation Improvements

### ISSUE THREAD

**Issue by ngardiner** [ngardiner/TWCManager#3]
Documentation, especially for modules are lacking. Target a few doco improvements per release for the next few releases leading up to v1.2.0:

v1.1.4:
- Fronius EMS Module **done**
- Powerwall2 EMS module **done**
- TED EMS module **done**

v1.1.5:

- Finish installation documentation **done**
- HASS EMS Module **done**
- HTTP Control Module **done**
- MQTT Control Module **inprog**
   - Details on topics and values to control
- WebIPC Control Module **inprog**

Future

- HASS Status Module
- MQTT Status Module

**Comment by one4spl** [comment]
Hi, on the subject of documentation the README.md stops at "To be completed shortly" 

Any chance you could spin through documenting a clean installation onto a new Rpi running a current OS?

**Comment by ngardiner** [comment]
Absolutely, will do shortly

**Comment by ngardiner** [comment]
I've made some progress on the documentation, with a more logical step through from installation of the OS to installation of the script. Would be great to get some feedback on whether it is helpful in installing TWCManager and if anything is missing that I could add.

**Comment by KCmangelma** [comment]
It sure is helpful to have all the steps laid out, but.. what if the red light is blinking, but the script output isn't really telling me what's wrong? Linkready messages are being sent at start, but no regular status updates are shown. Debug level turned up to 11, some messages and bytes are being ignored. All those fancy modules are no use it the basic serial communication isn't working :) Thanks.

**Comment by MikeBishop** [comment]
First, check in the manual that the blink code is that it's a slave without a master.  There are other reasons for error states, so make sure you're debugging the right one.  If there's more than 1-2 initial messages being ignored, my bet would be that it's not reading or sending the RS485 correctly.  (One or two ignored / invalid messages at start-up is normal, since it could have started listening mid-message.) I'd make sure that connection is using the right wires, etc.

**Comment by ngardiner** [comment]
Closing this, a lot of the documentation has been improved.
