### ISSUE TITLE
Storm Watch detection

### ISSUE THREAD

**Issue by MikeBishop** [ngardiner/TWCManager#31]
Powerwall's Storm Watch mode is not exposed via the local API that anyone has found so far.  However, it _is_ exposed on the cloud endpoint.  Particularly since the Tesla API tokens are already in the config for interacting with the Vehicle API, it should be feasible to check the cloud API for Storm Watch periodically.  Given that the point of Storm Watch is to trigger well in advance of it actually being needed, it would probably be sufficient to poll every 20-30 minutes.

This does break the current invariant that an unused charger doesn't continue to hit the cloud endpoint until the car is charged again.  Possible avenues I see:

- Change the invariant.  If you set this up, you expect it to hit the API.
- Require explicit opt-in for the Powerwall config to access the cloud API.
- Use the current API token, but never renew it from Powerwall checks.  Eventually, that token stops working if no car APIs renew it along the way.

**Comment by ngardiner** [comment]
These are good points! I think it is more than reasonable that we would consume the cloud endpoint if Powerwall functionality is enabled, and I think there is considerably less impact in doing so (in that consuming the vehicle API can wake vehicles), whereas I doubt any such penalty applies to Powerwalls.

Perhaps we could enable it by default for Powerwall (with documentation explaining this is the case) and disable it by override from the config? To me it seems like something that has a low cost associated with it (low intensity polling of the API), which may offer even more features in future due to the Cloud API being a bit more rich in data than the local endpoint, perhaps even a fallback should the local API become unavailable/get updated via firmware (not that the same couldn't happen to the Cloud API, of course).
