### ISSUE TITLE
No connection to TWCM during internet outage

### ISSUE THREAD

**Issue by danielsan1** [ngardiner/TWCManager#376]
Hi,

We experienced an internet outage for several hours yesterday. During the whole 3-4 hours my TWCManager installation was not reachable in my internal network. Is that normal behavior? Luckily my car was fully charged but otherwise I had no chance to charge because of the outage :-/ With the internet connection coming back also TWCM was reachable again. 
Can I avoid that behavior? 

And just a side question regarding 1.2.4.: I'm a bit confused... should I update to that version from 1.2.3 or not?

Thanks!

**Comment by MikeBishop** [comment]
That sounds like a local networking issue, rather than a TWCManager issue.  Certainly parts of TWCManager would not behave properly without Internet access, such as the Tesla API, but I'd be surprised if that kept the local web interface from being reachable.  Was the device reachable by other protocols, such as SSH?

**Comment by ngardiner** [comment]
Yes, there is no specific dependency on internet connectivity, but we are not very useful without it.
