### ISSUE TITLE
greenEnergyAmpsOffset polarity is reversed

### ISSUE THREAD

**Issue by MikeBishop** [ngardiner/TWCManager#64]
The fix should be simple regardless, but I'm not sure which would be less breaking to any existing users.  The comments in config.json suggest setting a _negative_ value for `greenEnergyAmpsOffset` to leave some buffer, but the current state of `check_green_energy()` treats this as a consumption report, meaning that a negative value will reduce the consumption reported by the other modules.

Do we update the comments to suggest a positive number, or do we modify `check_green_energy()` to multiply by negative one?  Or do we assume that no one wants to ignore part of their consumption and `abs()` it instead?

**Comment by ngardiner** [comment]
Good pickup! I feel like having a negative value for offset is probably a bit confusing but then again that is only my interpretation, to my mind a positive offset to the consumption means increasing it whilst a negative value would indeed reduce the consumption. 

I would be inclined to update the comments in the config file to use a positive value as I suspect anyone who has faithfully followed the comments has found it had the opposite effect and adjusted it. I am also not sure that limiting negative offset is a benefit, because it is possible that a system may provide a skewed value that can be offset using negative values in some very rare cases, so ultimately using a positive value provides 3 benefits: Makes more sense (imho), still allows negative bias for any system which requires it and is a minimal change overall.
